#!/bin/bash

if [ "$UID" -ne "0" ]
then
  echo "Merci de lancer le script avec sudo"
  exit 1
fi 

# variables
BASICS_SCRIPT_MIN_VERSION="1"

# vérifications
wget -qO - https://raw.githubusercontent.com/sedoo/Ubuntu_24.04_Scripts/main/version-check.sh | bash -s basics $BASICS_SCRIPT_MIN_VERSION || exit 1

# Ajout clé & dépot
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5 || exit 1

echo 'deb https://download.onlyoffice.com/repo/debian squeeze main' | tee -a /etc/apt/sources.list.d/onlyoffice.list

apt update

# Installation
apt install -y onlyoffice-desktopeditors || exit 1

echo ""
echo "*** Installation terminée ***"
