#!/bin/bash

if [ "$UID" -ne "0" ]
then
  echo "Merci de lancer le script avec sudo"
  exit 1
fi 

# variables
BASICS_SCRIPT_MIN_VERSION="1"

# vérifications
wget -qO - https://raw.githubusercontent.com/sedoo/Ubuntu_24.04_Scripts/main/version-check.sh | bash -s basics $BASICS_SCRIPT_MIN_VERSION || exit 1

# Placement dans le répertoire /tmp
cd /tmp

# Installation classique
wget https://ada.sedoo.fr/myprecious/PanoplyJ-5.5.5.tgz
tar -xzvf PanoplyJ-5.5.5.tgz || exit 1

rm -rf /opt/PanoplyJ
mv PanoplyJ/ /opt/

SHORTCUT_FOLDER=/usr/share/applications

mkdir -p $SHORTCUT_FOLDER

SHORTCUT_FILE=$SHORTCUT_FOLDER/panoply_sedoo.desktop

rm -f $SHORTCUT_FILE

touch $SHORTCUT_FILE
echo "[Desktop Entry]" >> $SHORTCUT_FILE
echo "Version=1.0" >> $SHORTCUT_FILE
echo "Type=Application" >> $SHORTCUT_FILE
echo "Name=Panoply" >> $SHORTCUT_FILE
echo "Icon=logviewer" >> $SHORTCUT_FILE
echo "Exec=/opt/PanoplyJ/panoply.sh %U" >> $SHORTCUT_FILE
echo "Categories=Science;" >> $SHORTCUT_FILE
echo "Terminal=false" >> $SHORTCUT_FILE
echo "Comment=Panoply" >> $SHORTCUT_FILE
echo "StartupWMClass=Panoply" >> $SHORTCUT_FILE

chown -R root:root /opt/PanoplyJ/

echo ""
echo "*** Installation terminée ***"
